### ISSUE TITLE
Exception thrown: write access violation. vertexloop was 0x????????.

### ISSUE THREAD

**Issue by nil-is-lin** [mrkkrj/TrianglePP#1]
When I port this project to a 64-bit platform, I get this problem. The "?" is some number in dex.

**Comment by mrkkrj** [comment]
Hi!
Sorry, I only used it on 32 bit back then! Will have a look at it at the Weekend (hope I'll find some time).

Regards,
Mrk

**Comment by mrkkrj** [comment]
Hi!
Some questions - what usecase ist that? Are you running the  trpp_example.cpp? Is the reported text a trace? I cannot find any of the strings in code.

Mrk

**Comment by nil-is-lin** [comment]
The problem in my case is happened in this:
1. clone the code, test and find it works well on 32 bit;
2. add new solution platform (x64) and change the target machine(x64);
3. test it in debug mode, it throw "Debug Assertion Failed!" and  "`Expression: (( mask &~ ( _MCW_DN | _MCW_EM | _MCW_RC ) ) == 0)`;
4. search the Internet, I find this "Take into account that on 64-bit platforms changing the floating-point precision is not supported. If the precision control mask `_MCW_PC` is used on a 64-bit platform a Debug Assertion Failed message will be displayed." see [here](https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/277738);
5. In this situation, I put the code "`#indefine _WIN64`" before "`_control87`" command to skip the changing the floating-point precision. However, it still throw the error  at the 14257 line of triangle_impl.hpp
(`x = vertexloop[0] = pointlist[coordindex++`];). 

Exception Thrown : `Exception thrown at 0x00007FF7B77E91EA in TrianglePP.exe: 0xC0000005: Access violation writing location 0x00000000F46D5010`.

I can not locate the problem result in this error, so I open this issue to get help.

**Comment by mrkkrj** [comment]
Thanks, will have a look! One question though: what compiler are you using?

**Comment by nil-is-lin** [comment]
Thanks for your reply. My OS is Windows 10.0.17134 and compiler is VS Community 2017 15.8.4.

**Comment by mrkkrj** [comment]
Hi! I found the problem, must only tidy up the code and push it to Github. Please have patience!

**Comment by mrkkrj** [comment]
fix uploaded, however there are warnings on x64 Windows because of wrong formats in printfs, is a TODO at the Moment.

**Comment by nil-is-lin** [comment]
Thank you for your prompt reply, it works well on my computer.

**Comment by mrkkrj** [comment]
nice to hear it, I hope there won't be more Errors :)
