### ISSUE TITLE
Can you add an ability to use segments? 

### ISSUE THREAD

**Issue by esacape3d** [mrkkrj/TrianglePP#2]
First of all, thank you so much for the great wrapper!

It works well with QT example and I'm trying to understand your codes with my humble C++ knowledge. 
When I looked into the tpp_impl.cpp, the segment part has not been implemented yet, but it's necessary to use holes or constraint outer lines from my understanding. 

Can you add this ability? 

Thank you in advance! 👍 

PS. I'm not familiar with Github yet, so I don't know posting an issue is okay or not. Please let me know if this would be deleted.

**Comment by mrkkrj** [comment]
Hi! 
I never thought this would be needed, but yes, I'll add this. Also because in that way one can create cool logos like the Triangle's logo itself!

**Comment by esacape3d** [comment]
Thank you! 
I'm looking for a constrained triangulation library and this would be the best if the segment parts are supported. 
Yes, one can triangulate logos and letters too 👍

**Comment by mrkkrj** [comment]
I think I could try to add it between Christmas and New Year, it that's OK for you.

**Comment by esacape3d** [comment]
That would be appreciated! Thanks!

**Comment by mrkkrj** [comment]
Hi! I added a first impl. for segment constraints. Is it enough for your use case?

**Comment by mrkkrj** [comment]
Not yet included in the GUI demonstrator, sorry!

**Comment by esacape3d** [comment]
Thank you so much! I'll check it out and let you know if I have further questions.

**Comment by mrkkrj** [comment]
Are the changes working? Do you need support for holes etc? 
I added segment visaulization to the GUI DemoApp.

**Comment by esacape3d** [comment]
@mrkkrj, sorry for the late reply. I have not tried yet but will check it next week. If you can revise the code to create holes, it would be nice. Thank you!

**Comment by mrkkrj** [comment]
Hi! I added 1st impl. of hole support and its visualisation in the DemoApp. Is this issue corrected with it?

Regards, Marek

**Comment by mrkkrj** [comment]
segments and holes seem to be working
