### ISSUE TITLE
Support for p tag

### ISSUE THREAD

**Issue by Yejneshwar** [mrkkrj/TrianglePP#3]
Hi,
Thank you for this implementation.

could you please add support for the D tag?

i.e. remove concavities

### EDIT :
I have fixed the issue, will be submitting a pull request soon.

Support for it existed but internally the "c" tag would still be added which caused the concavities to not be removed.

**Comment by mrkkrj** [comment]
Well, thanks! Cool job!

**Comment by mrkkrj** [comment]
Thank you! I will have a look at it to understand the fix. Could you maybe add a test case for it?
Regards,
Marek

**Comment by Yejneshwar** [comment]
Hey, quick question is there a way to extract the triangulation boundary? I'll add a fair few test cases and the ability to load files to the GUI (I don't know if the GUI can already do it). But might take some time.

Regards,
Yejneshwar Sivamoorthy

**Comment by mrkkrj** [comment]
Hi! Thanks for the message!

1. triangulation boudary - no, I didn't do anything in that direction
2. file loading in GUI - wanted to add that but never found time for that so far :-((

I still couldn't come round and test your pull request, sorry :-((... Had only a quick, cursory look at the code and it looked rather good for me! 

Regards,
Marek

**Comment by Yejneshwar** [comment]
Awesome!, I'll get started on them. See how it goes
