### ISSUE TITLE
Making mesh vertices and indices - is there a better way?

### ISSUE THREAD

**Issue by nothke** [mrkkrj/TrianglePP#5]
Thanks a lot for wrapping triangle! Made it a lot faster to implement.. But I have to say that using TrianglePP is a bit confusing.

What I want is to simply generate a tessellated mesh from a set of bounding points that will have non-overlapping vertices and indices that map to those vertices.

The solution I came up with is to use a face iterator, and then get points and use an unordered_map of Points with custom hasher to merge overlapping vertices manually. It's reasonably fast, but I have a feeling like there is a better/faster way to do it within this library. For example, I see a `checkForDuplicatePoints` but I am not sure how to use it. Reading through the code is unclear.

Here is a solution I am using right now:

``` c++
class PointHasher
{
public:
	using Point = tpp::Delaunay::Point;

	size_t operator() (const Point& key) const
	{
		std::size_t h1 = std::hash<double>{}(key[0]);
		std::size_t h2 = std::hash<double>{}(key[1]);
		return h1 ^ (h2 << 1);
	}
};

class PointKeyeq {
public:
	using Point = tpp::Delaunay::Point;

	bool operator() (const Point& p0, const Point& p1) const {
		return
			p0[0] == p1[0] &&
			p0[1] == p1[1];
	}
};
```
...
``` c++
const auto Regenerate = [&]() {

		inputPoints.clear();
		mesh.indices.clear();
		mesh.vertices.clear();

		// Make a circle of points
		{
			const float radX = genParams.radius;
			const float radY = genParams.radius;
			const float centerX = 0.f;
			const float centerY = 0.f;
			const int interpolations = genParams.circleSegments;

			float step = (2.f * glm::pi<float>()) / interpolations;

			for (int i = 0; i < interpolations; i++)
			{
				float theta = i * step;

				auto p = tpp::Delaunay::Point(
					centerX + (cos(theta) * radX),
					centerY + (sin(theta) * radY)
				);

				inputPoints.push_back(p);
			}
		}

		tpp::Delaunay gen(inputPoints);
		//gen.setMaxArea(0.3f);
		gen.setMinAngle(genParams.minAngle);
		gen.setMaxArea(genParams.maxArea);
		gen.TriangulateConf(true);

		using Point = tpp::Delaunay::Point;

		const auto ToVert = [](const Point& point) {
			Vertex v{ static_cast<float>(point[0]), static_cast<float>(point[1]), 0.f };
			v.colr = 0.0f;
			v.colg = 0.0f;
			v.colb = 0.0f;
			return v;
		};

		// Obtain points and triangles

		std::unordered_map<Point, int, PointHasher, PointKeyeq> vertMap; // For merging
		vertMap.reserve(1024);

		const bool _merge = mergeVertices;

		int index = 0;
		for (tpp::Delaunay::fIterator it = gen.fbegin(); it != gen.fend(); ++it)
		{
			Point p0; gen.Org(it, &p0); // These return index of a point in the input list (useless)
			Point p1; gen.Dest(it, &p1);
			Point p2; gen.Apex(it, &p2);

			if (_merge) // with vertex merging
			{
				const auto AddVert = [&](const tpp::Delaunay::Point& _p)
				{
					if (vertMap.contains(_p)) // use existing vertex
					{
						mesh.indices.push_back(vertMap[_p]);
					}
					else // create a new vertex
					{
						vertMap[_p] = index;
						mesh.indices.push_back(index);
						index++;

						mesh.vertices.push_back(ToVert(_p));
					}
				};

				AddVert(p0);
				AddVert(p1);
				AddVert(p2);

			}
			else // without vertex merging
			{
				mesh.indices.push_back(index++);
				mesh.indices.push_back(index++);
				mesh.indices.push_back(index++);

				mesh.vertices.push_back(ToVert(p0));
				mesh.vertices.push_back(ToVert(p1));
				mesh.vertices.push_back(ToVert(p2));
			}
		}

		if (!mesh.IsValid())
		{
			mesh.Build();
		}
		else
		{
			mesh.ReuploadVertices();
			mesh.ReuploadIndices();
		}

		mesh.RecalculateBounds();
	};
```

**Comment by mrkkrj** [comment]
Thanks for your interest in TrPP! 

I looked at your example and came up with something - is this what you wanted?

    tpp::Delaunay gen(inputPoints);

    gen.setMinAngle(genParams.minAngle);
    gen.setMaxArea(genParams.maxArea);
    gen.TriangulateConf(true);

    // use tpp::VertexIterator
    for (tpp::Delaunay::vIterator it = gen.vbegin(); it != gen.vend(); ++it)
    {
        auto vertexId = gen.vertexId(it); // internal ID
        auto pt = *it; // Point

        mesh.indices.push_back(vertexId); // OR: index++
        mesh.vertices.push_back(ToVert(pt));
    }

If not, what would be your ideal API?

Regards, 
Marek

**Comment by mrkkrj** [comment]
Ooops, just realized that's not quite what you wanted :-(... Will have another look.

PS:  checkForDuplicatePoints is a private method used to sanitize inputs, not to be used in the API, sorry!

**Comment by mrkkrj** [comment]
Ok, I think what you need is:

    tpp::Delaunay gen(inputPoints);
    gen.enableMeshGeneration();
    
    gen.TriangulateConf(true);
    
    std::vector<Point> points; 
    std::vector<int> indexes,

    gen.GetTriangulation(points, indexes);

bad news: not yet possible, good news: I will implement it sometimes next week (not that complicated!)...

**Comment by nothke** [comment]
Hey, thanks a lot for helping. I didn't have a chance to try it again since I posted.

I just wanted to say that looking at your suggestion, if you are already providing a function that takes in vectors, it would be better if it received std::span instead. In that way your function will be able to take any continuous array type, be it a C array[], std::array<T>, std::vector<T> or any other similar container. But I don't know what language standard you are targeting, because std::span is a c++20 feature. If that is not an option then a pointer with a size is better than a std::vector in my opinion.

But, another problem is that my Vertex struct is not a continuous array of double-based points, it has float positions, uvs and colors. That means that I will need to copy from an array of double-based points taken from gen.GetTriangulation() into my Vertex anyway. In that case, a lazy iterator is perhaps a better solution if it can avoid copies of potentially big arrays.

I have a few more comments but I don't have time to write right now. Just wanted to give a heads up on your current suggestions. I will come back to you tomorrow :)

**Comment by mrkkrj** [comment]
1. You mean you won't need GetTriangulation() at all? OK, an iterator is also possible.
2. I don't want to go to C++20(++) bacause of backward comp. But the idea is good, I could add some ifdefs and use C++20 goodies in the API
3. What everyone probably needed is support for own point type. I tried this out years ago, but maybe should do it this time

**Comment by nothke** [comment]
1. I don't need a magic GetTriangulation() if the iterator is easy to use.

One of the improvements I could suggest would be to add an ability for range-based for. so that instead of writing:
```cpp
for (tpp::Delaunay::fIterator it = gen.fbegin(); it != gen.fend(); ++it) {}
```
You could put a begin() and end() in the iterator, so you could write something sleeker like:
```cpp
for (auto& face : gen.faces()) {}
```
That would require a dereference as well, and right now I know you use the iterator as an input for `.Org` etc. So perhaps a wrapper for face-result would be necessary where you could `face.Dest(&p1);`. This would remove having to increment and deal with the iterator in user code so accidental mistakes can be reduced (and make it clearer to read).

2. I understand. std::span is not necessary, as I'm fine with 1.
3. I would probably implement a custom point type through a template. But that might be a bit too much for this library.

Thinking about the library here, my main issue might actually naming things 😅 I'm not a big fan of unnecessary shortening of vertex in `vIterator`, `vvIterator`, `veIterator` you have to search for each and look at the comment above. On the other hand, I typed `gen.` and started searching for `size..`, `number..`, `count..` nothing, until I found much later while just scrolling through the library it's actually `nvertices`, `nfaces`.. Where suddenly, the name "vertex" is not shortened, but "number" is. Very confusing.

**Comment by mrkkrj** [comment]
> Thinking about the library here, my main issue might actually naming things

I took over the old names from the old code by Piyush Kumar, thought about changin the names too, will probbaly do it (soonish)...

> I would probably implement a custom point type through a template.

Yes my idea too, will do it someday

> for (auto& face : gen.faces()) {}

Yes, wanted do it too

As you see, I concentated on adding new features before streamlining the original implementation...

**Comment by nothke** [comment]
That's good to hear! I can use the library as is right now with the way I do it in the original post. It's fast enough, but I was just wondering if it could be faster.

Looking forward to updates, but no rush!

**Comment by mrkkrj** [comment]
I implemented the following:

       tpp::Delaunay gen(inputPoints);
       gen.enableMeshIndexGeneration();
       
      for (tpp::FaceIterator it = gen.fbegin(); it != gen.fend(); ++it)
      {
         it.Org(p0, meshIdx0);
         insertMeshPt(p0, meshIdx0);

         it.Dest(p1, meshIdx1);
         insertMeshPt(p1, meshIdx1);

         it.Apex(p2, meshIdx2);
         insertMeshPt(p2, meshIdx2);
      }       
and also:

      for (const auto& f : gen.faces())
      {
         f.Org(p0, meshIdx0);
         insertMeshPt(p0, meshIdx0);

         f.Dest(p1, meshIdx1);
         insertMeshPt(p1, meshIdx1);

         f.Apex(p2, meshIdx2);
         insertMeshPt(p2, meshIdx2);
      }      

Caveat - tested only on Windows!

**Comment by mrkkrj** [comment]
guess I can closi this now
