### ISSUE TITLE
infinity loop 

### ISSUE THREAD

**Issue by Lozovik** [mrkkrj/TrianglePP#6]
Thank you for TrianglePP!
I'm using it in my FE analysis program.

I faced a problem in processing the polygon shape. 

If I use min_area  = 15000 the TrianglePP goes to infinity work but if I use 30000 or 10000 it works well.

I tried to understand the problem but did not succeed. I only found that  "enforcequality()" function gives us that infinity loop.

![image](https://github.com/mrkkrj/TrianglePP/assets/32809477/1e166cfb-5ad0-4323-af58-5b2e4dfda42a)
![image](https://github.com/mrkkrj/TrianglePP/assets/32809477/2353f20c-b643-418c-bb8d-60d8bc753554)

I guess that "enforcequality" gets not good input data because "while" loop from the original Triangle.c   

I've checked this data in the original Triangle it works well.

video:
https://drive.google.com/file/d/15pt8zoaFTUAHmuOHLiZOfiANkiIxnl-G/view?usp=sharing

my test function: 

int main()
{
      std::vector<Point> pslgPoints;
      std::vector<Point> pslgSegments;
     pslgPoints.push_back( Point( 96.38755452, 468.29728961 ));
     pslgPoints.push_back( Point( 96.38755452, 1083.30027734 ));
     pslgPoints.push_back( Point( 2029.39415452, 1044.64014531 ));
     pslgPoints.push_back( Point( 2029.39415452, 820.85321715 ));
     pslgPoints.push_back( Point( 2266.38760020, 816.11334821 ));
     pslgPoints.push_back( Point( 5096.38755452, 872.71353653 ));
     pslgPoints.push_back( Point( 5096.38755422, 257.71036145 ));
     pslgPoints.push_back( Point( 1859.23857089, 284.39844942 ));
     pslgPoints.push_back( Point( 1021.25668363, 449.67990700 ));
     pslgSegments.push_back( Point( 96.38755452, 468.29728961 ));
     pslgSegments.push_back( Point( 96.38755452, 1083.30027734 ));
     pslgSegments.push_back( Point( 96.38755452, 1083.30027734 ));
     pslgSegments.push_back( Point( 2029.39415452, 1044.64014531 ));
     pslgSegments.push_back( Point( 2029.39415452, 1044.64014531 ));
     pslgSegments.push_back( Point( 2029.39415452, 820.85321715 ));
     pslgSegments.push_back( Point( 2029.39415452, 820.85321715 ));
     pslgSegments.push_back( Point( 2266.38760020, 816.11334821 ));
     pslgSegments.push_back( Point( 2266.38760020, 816.11334821 ));
     pslgSegments.push_back( Point( 5096.38755452, 872.71353653 ));
     pslgSegments.push_back( Point( 5096.38755452, 872.71353653 ));
     pslgSegments.push_back( Point( 5096.38755422, 257.71036145 ));
     pslgSegments.push_back( Point( 5096.38755422, 257.71036145 ));
     pslgSegments.push_back( Point( 1859.23857089, 284.39844942 ));
     pslgSegments.push_back( Point( 1859.23857089, 284.39844942 ));
     pslgSegments.push_back( Point( 1021.25668363, 449.67990700 ));
      pslgSegments.push_back( Point( 1021.25668363, 449.67990700 ));
      pslgSegments.push_back( Point( 96.38755452, 468.29728961 ));

      int expected = 0;
      bool withQuality = true;

    Delaunay trPlsgGenerator(pslgPoints);
    trPlsgGenerator.enableMeshIndexGeneration();  // For Iterating using mesh indexes
   
    double min_area = 15000;
    trPlsgGenerator.setMinAngle(30.5f);
    trPlsgGenerator.setMaxArea(min_area);

    bool segmentsOK = trPlsgGenerator.setSegmentConstraint(pslgSegments);

    trPlsgGenerator.Triangulate(withQuality);
      std::vector< std::vector<double> > mesh_;
      std::vector<std::vector<int>> vertices_to_triangles;

           // iterate over triangles
        std::set<int> vertIds;

        Delaunay::Point p0, p1, p2;
        int meshIdx0 = -1, meshIdx1 = -1, meshIdx2 = -1;

        for (FaceIterator fit = trPlsgGenerator.fbegin(); fit != trPlsgGenerator.fend(); ++fit)
        {

            fit.Org(p0, meshIdx0);  // queries the mesh index!
            fit.Dest(p1, meshIdx1);
            fit.Apex(p2, meshIdx2);
             vertIds.insert(meshIdx0);
             vertIds.insert(meshIdx1);
            vertIds.insert(meshIdx2);
            vertices_to_triangles.push_back({meshIdx0, meshIdx1, meshIdx2});
            double x1 = -1;
            double y1 = -1;
            double x2 = -1;
            double y2 = -1;
            double x3 = -1;
            double y3 = -1;
            x1 = p0[0]; y1 = p0[1];
            x2 = p1[0]; y2 = p1[1];
            x3 = p2[0]; y3 = p2[1];
            mesh_.push_back({p0[0], p0[1]});
            mesh_.push_back({p1[0], p1[1]});
            mesh_.push_back({p2[0], p2[1]});
            mesh_.push_back({p0[0], p0[1]});
            //std::cout << "[[" << x1 << ", " << y1 << "], " << "[" << x2 << ", " << y2 << "], " << "[" << x3 << ", " << y3 << "]," << "[" << x1 << ", " << y1 << "]],\n";
            std::cout << "[" << meshIdx0 << ", " << meshIdx1 << ", " << meshIdx2 << "]\n";
        }
   return 0;
}

**Comment by mrkkrj** [comment]
Hi,
Sorrry for the delay: Thank you for this bug, I saw some similiar problems when playing with the demonstrator.
Will have a look soon.

Regards,
Marek

**Comment by mrkkrj** [comment]
1st insight - a quick hack is to set: 

    trPlsgGenerator.useConvexHullWithSegments(true);

Of course if that is what you need, i.e. if you are not using holes. I keep investigatigating!

**Comment by mrkkrj** [comment]
seems to be internal error in TriLib:

    if (countingtri.tri == m->dummytri) {
      printf("Internal error in deletevertex():\n");
      printf("  Attempt to delete boundary vertex.\n");
      internalerror();
    }

I'll try to fix it.

**Comment by Lozovik** [comment]
Hi Marek,

I am using holes quite often.
Thanks

Regards,
Sergey

**Comment by mrkkrj** [comment]
I mean if you need holes + convex hull.

Sorry that it will probably take more time to fix than usual, bc. it's a TriLib bug, but we will get there!

Regards,
Mrk

**Comment by Lozovik** [comment]
Hi Marek,

No problem. Don't rush. Now I am working on another part of my project. I can wait.
Thanks 👍🏻

Regards,
Sergey

**Comment by mrkkrj** [comment]
Hi Sergey,
I just added a fix for your example. Additionally, some sanity checks are now enabled and will throw an exception in case of internal errors like that one. You can disable it, of course, have a look in the Docs section.

Regards,
Marek

**Comment by Lozovik** [comment]
Hi Marek,

Thank you so much!

**Comment by mrkkrj** [comment]
thank you for reporting!
